lis =[
"had"
,"that she could find"
,"and take it to"
,"her fairy godmother dug"
,"hit it with her wand"
,"the pumpkin transformed"
,"she went to see"
,"she found"
,"she said"
,"that which made"
,"Cinderella wore it"
,"The fairy took one"
,"it changed"
,"never seen before"
,"she told him"
,"she didn’t have them"
,"the FGM would change them "
,"who would ride"
,"they wouldn’t do anything"
,"the fairy said"
,"her FGM only touched"
,"his clothes were changed"
,"she gave him"
,"she stopped, she mounted"
,"her FGM recommended"
,"she promised"
,"we had to warn"
,"ran"
,"he gave her"
,"led her "
,"A great silence was made"
,"everyone stopped dancing"
,"the violins didn’t play as much"
,"that he happened "
,"the son of the king placed her"
,"took her"
,"she danced"
,"all admired her"
,"everyone wore"
,"didn’t eat anything"
,"She went to sit down"
,"she made them "
,"she made them"
,"which astonished them greatly"
,"she heard the clock strike 11:45"
,"she made a great reverence"
,"she left as fast as she could"
,"As soon as she arrived, she went to find her FGM"
,"The two sisters knocked on the door; Cinderella went to open it"
,"All she had to do was wake up"
]

for i in range(len(lis)):
    lis[i] = f"{i+1}." + lis[i][0].upper() + lis[i][1:] + "\n"

with open("quicky.txt", "w") as f:
    f.writelines(lis)